### ISSUE TITLE
Unused table value on leftJoin

### ISSUE THREAD

**Issue by OnofreTZK** [JordanMarr/SqlHydra#104]
I need to left join some tables, but I'm facing a problem in that I don't know what is happening

```fsharp
open SqlHydra.Query
open Database.Generated

...


let hash = "placeholder"
let! result =
      selectAsync HydraReader.Read (Shared ctx) {
              for mt in ``public``.maintablename do
              leftJoin sf in ``public``.outertablename on ((mt.attr1, mt.attr2) = (sf.Value.attr1, sf.Value.attr2))
              where (mt.hash = hash)
              select ( mt.attribute_name, Some sf.Value.attribute)
     }

// Error thrown:
// error FS1182: The value 'sf' is unused.
```

My `.toml`:

```toml
[general]
connection = "{connectionString}"
output = "Generated/Database.Generated.fs"
namespace = "Database.Generated"
nullable_property_type = "Option"
cli_mutable = false
[sqlhydra_query_integration]
provider_db_type_attributes = true
table_declarations = true
[readers]
reader_type = "Npgsql.NpgsqlDataReader"
[filters]
include = ["multitenancy/*", "public/*"]
exclude = [ ]
```

Could you help me, @JordanMarr ?
