### ISSUE TITLE
`deleteAll` failing with SqlHydra.Query 1.1.0

### ISSUE THREAD

**Issue by MangelMaxime** [JordanMarr/SqlHydra#46]
Using the following code with SqlHydra.Query 1.1.0 result in an error at runtime:

```fs
module Tables =

    let encounterForms = table<dbo.EncounterForms>

    let! _ =
        deleteAsync (Shared ctx) {
            for _ in Tables.encounterForms do
                deleteAll
        }
```

```
System.NotImplementedException: The method or operation is not implemented.
   at SqlHydra.Query.QuotationVisitor.visit@10(FSharpExpr expr)
   at SqlHydra.Query.QuotationVisitor.visitFor[T](FSharpExpr`1 f)
   at SqlHydra.Query.DeleteBuilders.DeleteBuilder`1.For[T](QuerySource`1 state, FSharpExpr`1 forExpr)
   at Antidote.Server.Tests.Database.clean@57-1.Invoke(QueryContext _arg1) in /Users/mmangel/Workspaces/Github/Antidote-AI/antidote-apps/Server/Antidote.Server.Tests/Database.fs:line 73
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 510
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 112
```

Downgrading to SqlHydra 1.0.5 with the following code:

```fs
module Tables =

	let encounterForms = table<dbo.EncounterForms> |> inSchema (nameof dbo)

    let! _ =
        deleteAsync (Shared ctx) {
            for _ in Tables.encounterForms do
                deleteAll
        }
```

works.

**Comment by JordanMarr** [comment]
Ok, I think that should be a simple fix.

**Comment by MangelMaxime** [comment]
In case it helps here is the configuration file I am using:

```toml
[general]
connection = "Server=127.0.0.1,33300;Database=XXX;User Id=SA;Password=XXXXXXXX;TrustServerCertificate=True"
output = "Server/Antidote.Database/Dbos.fs"
namespace = "Antidote.Database"
cli_mutable = false
[readers]
reader_type = "Microsoft.Data.SqlClient.SqlDataReader"
[filters]
include = []
exclude = []
```

With `sqlhydra.sqlserver@1.1.1`
