### ISSUE TITLE
Generate types in GitHub workflow generates no table types

### ISSUE THREAD

**Issue by stoft** [JordanMarr/SqlHydra#87]
I'm mostly in need of rubber ducking here and ideas on how to debug this I think and don't know where else to turn. 🙂 

I've added a GitHub workflow action that will auto-generate types and `git diff` them against the types in the PR with the goal of failing the build if there is a diff.

Problem: for some reason the generator is not generating the types for the tables, only the general types.

Environment:
- postgres 12.17
- .NET 8
- ubuntu:latest

Debugging and known so far:
- works locally
- our DB migration tool works in the GH workflow, and other test scripts that access the DB (nodejs) that we have since previously
- setting the wrong password in the `toml` causes SqlHydra.Cli to throw an error

Workflow steps:
```yaml
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          global-json-file: global.json
          
      - name: Check generated DB types are up to date with the DB
        run: |
          dotnet tool restore

          ls -l src/Library/generated

          make generate-db-types

          ls -l src/Library/generated
          git diff --exit-code
```

I've added the `ls -l` just to show the size diff before and after. `make generate-db-types` is equal to `dotnet sqlhydra npgsql --project ...`

Output:
```plaintext
Tool 'fantomas' (version '6.2.3') was restored. Available commands: fantomas
Tool 'sqlhydra.cli' (version '2.3.3') was restored. Available commands: sqlhydra

Restore was successful.
total 16
-rw-r--r-- 1 runner docker 14442 Mar 14 15:49 DatabaseTypes.fs
dotnet sqlhydra npgsql --project src/Library/Library.fsproj
- SqlHydra.Npgsql
- v2.3.3.0
- '/home/runner/work/myproject/myproject/src/Library/generated/DatabaseTypes.fs' has
been generated!
total 8
-rw-r--r-- 1 runner docker 6546 Mar 14 15:50 DatabaseTypes.fs
diff --git a/src/Library/generated/DatabaseTypes.fs b/src/Library/generated/DatabaseTypes.fs
index 4dab217..eb75328 100644
--- a/src/Library/generated/DatabaseTypes.fs
+++ b/src/Library/generated/DatabaseTypes.fs
@@ -31,136 +31,6 @@ module private DataReaderExtensions =
             reader.GetFieldValue(ordinal) |> System.TimeOnly.FromTimeSpan
         
 
-module myschema = ...
```

Here we can see the size has more than halved and the diff is in reality about 200 lines removed.

Thanks for a great tool! Any ideas on how to debug this would be greatly appreciated. ❤️
